### ISSUE TITLE
less annoying api in asp.net mvc

### ISSUE THREAD

**Issue by WizardKid** [LessAnnoyingCRM/LessAnnoyingCRM.github.io#1]
Hi is there a way to integrate less annoying into an asp.net mvc contact form?

**Comment by tilikang** [comment]
That should be possible, yes. We don't have sample code specifically for ASP, but [this tutorial](https://www.lessannoyingcrm.com/help/tutorial-integrating-a-web-form-with-less-annoying-crm) shows how to get it working with plain html and PHP. The concepts should be the same with asp.net.

**Comment by WizardKid** [comment]
Asp.net uses controllers, not show how the api would call to LACRM without the help of the controllers

**Comment by tilikang** [comment]
I'm afraid that we can't provide support for your specific coding environment. Our API can be called from any programming language, you just need to make an https request to our endpoint.

**Comment by WizardKid** [comment]
I have created a working api for asp.net mvc.. Thank you for your fast response

**Comment by WizardKid** [comment]
Hi I don't mean to bother you but I am having a little bit of issue in regards to the customfields not showing in the crm. the api is successful but when I clicked the contact, only the Contact Name is there. There are no emails or the value of the custom fields. I have followed the documentation to the T and unable to work out why the customfields not showing in the contact info. here is my code:
`public async Task<bool> phpVersion(Booking booking)
        {
            return true;
        }
        public async Task<bool> createContact(Booking booking)
        {
          
            string url = "https://api.lessannoyingcrm.com?APIToken=apitokenremoved&UserCode=removed&Function=CreateContact&PipelineId=removed?StatusId=3687195324549534588370879140406";
            var postData = new List<KeyValuePair<string, string>>
            {

                new KeyValuePair<string, string>("FullName",booking.Name),
                new KeyValuePair<string, string>("Email",booking.Email)
            };

            postData.Add(new KeyValuePair<string, string>
                (
                    "Email[0]", (new KeyValuePair<string, string>("Text", booking.Email),
                                new KeyValuePair<string, string>("Type", "Work")).ToString()
                ));

            postData.Add(new KeyValuePair<string, string>
               (
                   "Phone[0]", (new KeyValuePair<string, string>("Text", booking.Phone),
                               new KeyValuePair<string, string>("Type", "Work")).ToString()
               ));



            postData.Add(new KeyValuePair<string, string>
               (
                   "Website[0]", (new KeyValuePair<string, string>("Text", "www.google.com")).ToString()
               ));


            postData.Add(new KeyValuePair<string, string>
               (
                   "Location[0]", (
                                new KeyValuePair<string, string>("Text", booking.PostCode)
                                                                
                               ).ToString()
               ));

            postData.Add(new KeyValuePair<string, string>
                (

                    "CustomFields", (

                        new KeyValuePair<string,string>("Conservatory",booking.Consevatory),
                        new KeyValuePair<string,string>("Size",booking.Size),
                        new KeyValuePair<string,string>("Type",booking.RoofType),
                        new KeyValuePair<string,string>("Source",booking.HearAboutUs),
                        new KeyValuePair<string, string>("Location", booking.PostCode),
                        new KeyValuePair<string,string>("Comment",booking.OtherInfo),
                        new KeyValuePair<string, string>("Conservatory", booking.SelectedProduct)


                    ).ToString()


                ));`

This is done in C# asp.net mvc

**Comment by tilikang** [comment]
I'm not super familiar with how C# formats form data, but I'd guess the issue is that the fields aren't being formatted correctly. One thing you can do is look at the API logs at the bottom of your [API settings page](https://account.lessannoyingcrm.com/app/Settings/Api). That'll show you all the requests you've made recently, so you might be able to tell if the parameters are getting passed to us correctly or not.

If that's still not working, it might be helpful to post the actual JSON that's generated by all those `postData.Add` functions. I can't really help debug based on the code since I don't know C#, but if you show me the raw JSON you're sending us, I might be able to figure out what's wrong.

**Comment by WizardKid** [comment]
Hi sorry i haven't gotten back to you.. This is the api log for the post: 
`Parameters: {"PipelineId":"3727019319364096972431828675722","FullName":"John Doe","Email":["([Text, example@example.com], [Type, Work])"],"Phone":["([Text, 5555555555], [Type, Work])"],"Website":["[Text, ]"],"Location":"[, john street]","CustomFields":"([Conservatory, Glass], [Size, 3.33 x 3.33 Metres], [Type, ], [Source, Newspaper], [Comment, testing api], [Conservatory, Lean-To])"} Response: {"ContactId":"3727243229049634192380189957314","Success":true}`
the only field posting is the `FullName`

**Comment by tilikang** [comment]
That doesn't look like valid JSON to me. I pasted it in at https://jsonformatter.org/json-parser at it gave an error.

Here's at least one example of an issue: `"Email":["([Text, example@example.com], [Type, Work])"]` has double quotes around the entire value between the brackets (`[`).

**Comment by WizardKid** [comment]
I want to let you know that I have built a fully working api for the LACRM SYSTEM.. for CreateContact and Pipeline/StatusID

**Comment by tilikang** [comment]
That's great, congrats!
